music_app/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:new, :create, :show]
  resource :session, only: [:new, :create, :destroy]
  resources :bands do
    resources :albums, only: [:new]
  end
  resources :albums do
    resources :tracks, only: [:new]
  end
  resources :tracks

end

music_app/app/models/album.rb
class Album < ApplicationRecord

  validates :title, :year, presence: true

  belongs_to :band 
end

music_app/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

music_app/app/models/band.rb
# == Schema Information
#
# Table name: bands
#
#  id         :bigint(8)        not null, primary key
#  name       :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Band < ApplicationRecord
  validates :name, presence: true, uniqueness: true

  
end

music_app/app/models/track.rb
class Track < ApplicationRecord
  validates :lyrics, :name, :ord, presence: true
  validates :ord, uniqueness: {scope: :album_id}

  belongs_to :album

  has_one :band,
    through: :album,
    source: :band

  
end

music_app/app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :bigint(8)        not null, primary key
#  email           :string           not null
#  password_digest :string           not null
#  session_token   :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ApplicationRecord
  validates :email, :password_digest, :session_token, presence: true
  validates :email, uniqueness: true
  validates :password, length: {minimum: 6}, allow_nil: true

  after_initialize :ensure_session_token

  attr_reader :password

  def self.generate_session_token
    SecureRandom::urlsafe_base64
  end

  def reset_session_token!
    self.session_token = self.class.generate_session_token
    self.save!
    self.session_token
  end

  def ensure_session_token
    self.session_token ||= self.class.generate_session_token
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def self.find_by_credentials(email, password)
    user = User.find_by(email: email)
    return nil if !user
    user.is_password?(password) ? user : nil
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

end

music_app/app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  def show
    @album = Album.find_by(id: params[:id])
    render :show
  end

  def new
    @band = Band.find_by(id: params[:band_id])
    @album = Album.new(band_id: params[:band_id])
    render :new
  end

  def create
    @album = Album.new(album_params)
    if @album.save
      redirect_to album_url(@album)
    else
      flash.now[:errors] = @album.errors.full_messages
      render :new
    end
  end

  def edit
    @album = Album.find_by(id: params[:id])
    render :edit
  end

  def update
    @album = Album.find_by(id: params[:id])
    if @album.update(album_params)
      redirect_to album_url(@album)
    else
      flash.now[:errors] = @album.erros.full_messages
      render :edit
    end
  end

  def destroy
    @album = Album.find_by(id: params[:id])
    @album.destroy
    redirect_to band_url(@album.band_id)
  end

  private
  def album_params
    params.require(:album).permit(:create, :destroy)
  end
end

music_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user, :logged_in?

  def current_user
    return nil unless session[:session_token]
    @current_user ||= User.find_by(session_token: session[:session_token])
  end

  def login!(user)
    session[:session_token] = user.reset_session_token!
  end

  def logout!
    current_user.reset_session_token!
    session[:session_token] = nil
  end

  def logged_in?
    !!current_user
  end

  def require_user!
    redirect_to new_session_url unless logged_in?
  end
end

music_app/app/controllers/bands_controller.rb
class BandsController < ApplicationController
  before_action :require_user!

  def index
    @bands = Band.all
    render :index
  end

  def show
    band = Band.find_by(name: name)
    render :show
  end

  def new
    @band = Band.new
    render :new
  end

  def create
    @band = Band.new(band_params)
    if @band.save
      redirect_to bands_url
    else
      flash.now[:errors] = @band.errors.full_messages
      render :new
    end
  end

  def edit
    @band = Band.find(params[:id])
    render :edit
  end

  def update
    @band = Band.find(params[:id])
    if @band.update(band_params)
      redirect_to band_url(@band)
    else
      flash.now[:errors] = @band.errors.full_messages
      render :edit
    end
  end

  def destroy
    @band.destroy
    redirect_to bands_url
  end

  private
  def band_params
    params.require(:band).permit(:name)
  end
end

music_app/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    render :new
  end

  def create
    user = User.find_by_credentials(
        params[:user][:email],
        params[:user][:password]
    )

    if user
      login!(user)
      redirect_to user_url
    else
      flash.now[:errors] = ['Create your account first']
      render :new
    end
  end

  def destroy
    logout!
    redirect_to new_session_url
  end
end

music_app/app/controllers/tracks_controller.rb
class TracksController < ApplicationController
  def show
    @track = Track.find(param[:id])
    render :show
  end

  def new
    @track = Track.new
    render :new
  end

  def create
    @track = Track.new(track_params)
    if @track.save
      redirect_to track_url(@track)
    else
      @album = track.album
      flash.now[:errors] = @track.errors.full_messages
      render :new
    end
  end

  def edit
    @track = Track.find_by(id: params[:id])
    render :edit
  end

  def update
    @track = Track.find_by(id: params[:id])
    if @track.update
      redirect_to track_url(@track)
    else
      flash.now[:errors] = @track.errors.full_messages
      render :edit
    end
  end

  def destroy
    @track = Track.find_by(id: params[:id])
    @track.destroy
    redirect_to album_url(@track.album_id)
  end

  def track_params
    params.require(:track).permit(:album_id, :title, :ord)
  end
end

music_app/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    render :show
  end

  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      login!(@user)
      redirect_to new_session_url
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  private
  def user_params
    params.require(:user).permit(:email, :password)
  end
end

music_app/app/helpers/albums_helper.rb
module AlbumsHelper
end

music_app/app/helpers/application_helper.rb
module ApplicationHelper
  def auth_token
    "<input
        type=\"hidden\"
        name=\"authenticity_token\"
        value=\"#{ form_authenticity_token }\">".html_safe
  end
end

music_app/app/helpers/tracks_helper.rb
module TracksHelper
end

music_app/app/views/albums/index.html.erb
a

music_app/app/views/bands/_form.html.erb
<% action_url = band.persisted? ? band_url(band) : bands_url %>
<% http_method = band.persisted? ? "PATCH" : "POST" %>

<form class='form' action="<%= action_url %>" method="POST">
  <input type="hidden" name="_method" value="<%= http_method %>">
  <%= auth_token %>
  <p>
    <label for='band-name'>Name</label>
    <input id='band-name' type="text" name="band[name]" value="<%= band.name %>">
  </p>

  <input type="submit">
</form>

music_app/app/views/bands/edit.html.erb
<h1>Edit <%=@band.name%> </h1>

<%= render 'form', band: @band %>

music_app/app/views/bands/index.html.erb
<h1> All bands: </h1>

<ul>
    <% @bands.each do |band| %>
      <li>  <%= band.name %>  </li>
    <% end %>
</ul>

music_app/app/views/bands/new.html.erb
<h1> New crew! </h1>

<%= render 'form', band: @band %>

music_app/app/views/bands/show.html.erb
<h1> Band: <%= @band.name %></h1>

<%= link_to "Edit", edit_band_url(@band) %>
<%= link_to "Create an album", new_band_album_url(@band) %>
<%= link_to "Delete band", @band, method: :delete %>

music_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MusicApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="/css/master.css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <ul><%= link_to "Home",   '#' %></ul>
            <ul><%= link_to "Help",   '#' %></ul>
            <ul><%= link_to "Contact Us", '#' %></ul>

          </ul>
        </nav>
      </div>
    </header>
    <% if logged_in? %>
      <p>Signed in as: <%= current_user.email %></p>
      <form action=<%= session_url %> method="post">
        <input type="hidden" name="_method" value="delete">
        <%= auth_token %>
        <input type="submit" value="Log out">
      </form>
    <% end %>

    <%= yield %>
  </body>
</html>

music_app/app/views/users/new.html.erb
<h1> Create an account: </h1>

<form class="form" action="<%=users_url%>" method="post">
  <%= auth_token %>

  <p>
    <label>Email:
      <input type="text" name="user[email]" value="">
    </label>
  </p>
  <p>
    <label>Password:
      <input type="password" name="user[password]" value="">
    </label>
  </p>
  <input type="submit" name="" value="Create my account">
</form>

<br>
<a class='button' href=<%= new_session_url %> >Sign-in</a>

music_app/app/views/users/show.html.erb
<h1> User Profile </h1>
<p>
  <%= current_user.email %>
</p>